### ISSUE TITLE
Documentation / Guide / Introduction / Schema

### ISSUE THREAD

**Issue by allozaur** [vue-wordpress/core#54]
Create illustrations for module's Lifecycle Schema

**Comment by Fifciu** [comment]
![schema01](https://user-images.githubusercontent.com/30155292/58325963-bfea2f00-7e2b-11e9-962b-e2540e139957.jpg)
# Data Interpretation Schema
- TheRoot (first abstraction layer) component gets Fetched Data as props called **data**
- Props' Validator checks whether **data** has a certain shape (contains certain keys etc.)
- Inside render function, component separating **data** for sections (rows)
- Then, it renders separated Sections as fragments (Root node is not necessary!)

![schema02](https://user-images.githubusercontent.com/30155292/58326752-0a6cab00-7e2e-11e9-9882-92e511350806.jpg)


## Inside of each Section
- Section (second abstraction layer) interprets provided **data** and separate it for columns (default 1 column)
- Then, it renders separated fragments as columns or **error fallback component**

## Inside of each Column
- It renders **Block** component with content based on provided props

@allozaur

**Comment by allozaur** [comment]
![schema_sketch](https://user-images.githubusercontent.com/37627284/59305224-1d8ad200-8c9a-11e9-9a6b-4112b901e75d.jpg)

**Comment by Fifciu** [comment]
- [ ] Describe Lifecycle

**Comment by Fifciu** [comment]
https://docs.vuewordpress.io/guide/introduction/schema/
